#!/bin/sh /etc/rc.common

START=98

SERVICE_PID_FILE=/var/run/awa_clientd.pid
BINARY=/bin/awa_clientd
LOGFILE=/var/log/awa_clientd

apply_global_settings() {
	. /etc/config/awalwm2m
}

start() {
	apply_global_settings
	start-stop-daemon -m -S -p $SERVICE_PID_FILE -b -x $BINARY -- -l $LOGFILE --bootstrap $BOOTSTRAP $VERBOSE
}

stop() {
	start-stop-daemon -K -p $SERVICE_PID_FILE -s 15
	rm -f $SERVICE_PID_FILE
}
