#!/bin/sh /etc/rc.common

START=98

SERVICE_PID_FILE=/var/run/awa_bootstrapd.pid
BINARY=/bin/awa_bootstrapd
LOGFILE=/var/log/awa_bootstrapd
LOCAL_CONFIG=/etc/lwm2m/bootstrap-contiki.config
FLOW_CONFIG=/etc/lwm2m/bootstrap-contiki-flow-NAT64.config
PORT=15683

apply_global_settings() {
	. /etc/config/awalwm2m
}

start() {
	sleep 5
	apply_global_settings
	start-stop-daemon -m -S -p $SERVICE_PID_FILE -b -x $BINARY -- -l $LOGFILE --interface $INTERFACE --addressFamily $ADDRESS_FAMILY --port $PORT --config $LOCAL_CONFIG --config $FLOW_CONFIG $VERBOSE
}

stop() {
	start-stop-daemon -K -p $SERVICE_PID_FILE -s 15
	rm -f $SERVICE_PID_FILE
}
